name: Nx CI + CD (Railway Docker Ready)

on:
  push:
    branches:
      - main

jobs:
  verify:
    name: Lint • Test • Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install dependencies
        run: npm install
      - name: Nx Affected - Lint
        run: npx nx affected --target=lint --parallel=3
      - name: Nx Affected - Test
        run: npx nx affected --target=test --parallel=3
      - name: Nx Affected - Build
        run: npx nx affected --target=build --parallel=3

  deploy:
    name: Deploy API + Web
    runs-on: ubuntu-latest
    needs: verify
    strategy:
      matrix:
        service: [api, web]
      max-parallel: 1
    steps:
      - uses: actions/checkout@v4
      - name: Install Railway CLI
        run: npm install -g @railway/cli
      - name: Deploy via Railway
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
        run: |
          set -e
          retries=3
          if [ "${{ matrix.service }}" == "api" ]; then
            SERVICE_ID=896433a2-649c-4d47-b397-1c2e4918b4fe
            DOCKERFILE=.railway/dockerfile.api
          else
            SERVICE_ID=651af99c-48dd-4d98-85f4-a0bc78710924
            DOCKERFILE=.railway/dockerfile.web
          fi

          until [ $retries -le 0 ]; do
            echo "Deploying ${{ matrix.service }}..."
            # 👇 root (.) context + explicit Dockerfile
            railway up --ci --service $SERVICE_ID --dockerfile $DOCKERFILE . && break
            retries=$((retries-1))
            echo "Retrying deploy for ${{ matrix.service }}... ($retries left)"
            sleep 10
          done
