name: Nx CI + CD (Stable & Reliable)

on:
  push:
    branches:
      - main

concurrency:
  group: deploy-${{ github.ref }}
  cancel-in-progress: false

jobs:
  verify:
    name: Lint • Test • Build (affected only)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Nx Affected - Lint
        run: npx nx affected --target=lint --parallel=3

      - name: Nx Affected - Test
        run: npx nx affected --target=test --parallel=3

      - name: Nx Affected - Build
        run: npx nx affected --target=build --parallel=3

  deploy:
    name: Deploy API + Web Sequentially
    runs-on: ubuntu-latest
    needs: verify
    timeout-minutes: 30
    strategy:
      matrix:
        service: [api, web]
      max-parallel: 1   # sequential run for stability
    steps:
      - uses: actions/checkout@v4

      - name: Install Railway CLI
        run: npm install -g @railway/cli

      - name: Deploy
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
        run: |
          set -e
          retries=3
          if [ "${{ matrix.service }}" == "api" ]; then
            SERVICE_ID=896433a2-649c-4d47-b397-1c2e4918b4fe
            PATH_DOCKER=.railway/api
          else
            SERVICE_ID=651af99c-48dd-4d98-85f4-a0bc78710924
            PATH_DOCKER=.railway/web
          fi

          until [ $retries -le 0 ]; do
            railway up --ci --service $SERVICE_ID --path $PATH_DOCKER && break
            retries=$((retries-1))
            echo "Retrying deploy for ${{ matrix.service }}... ($retries left)"
            sleep 10
          done
