name: CI/CD Deploy to Railway

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      API_SERVICE_ID: ${{ secrets.RAILWAY_API_SERVICE_ID }}
      WEB_SERVICE_ID: ${{ secrets.RAILWAY_WEB_SERVICE_ID }}
      RAILWAY_API_KEY: ${{ secrets.RAILWAY_API_KEY }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install Railway CLI
        run: |
          curl -fsSL https://raw.githubusercontent.com/railwayapp/cli/master/install.sh | sh
          railway --version

      - name: Login to Railway
        run: railway login --apiKey $RAILWAY_API_KEY

      # ---------------- API Deploy ----------------
      - name: Deploy API
        working-directory: apps/api
        run: railway up --ci --service $API_SERVICE_ID

      # ---------------- Web Deploy ----------------
      - name: Deploy Web
        working-directory: apps/web
        run: railway up --ci --service $WEB_SERVICE_ID
