name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest

    env:
      NODE_ENV: production

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run Lint
        run: npx nx lint

      - name: Run Tests
        run: npx nx test --ci --code-coverage

      - name: Build Apps
        run: npx nx build api && npx nx build web

      - name: Install Railway CLI
        run: curl -sSL https://railway.app/install.sh | sh

      - name: Deploy API to Railway
        run: |
          SERVICE_ID=896433a2-649c-4d47-b397-1c2e4918b4fe
          RETRIES=3
          until [ $RETRIES -le 0 ]; do
            railway up --ci --service $SERVICE_ID . && break
            echo "Retrying deploy for API... ($RETRIES left)"
            RETRIES=$((RETRIES-1))
            sleep 5
          done
          if [ $RETRIES -le 0 ]; then
            echo "API deploy failed after retries"
            exit 1
          fi

      - name: Deploy Web to Railway
        run: |
          SERVICE_ID=651af99c-48dd-4d98-85f4-a0bc78710924
          RETRIES=3
          until [ $RETRIES -le 0 ]; do
            railway up --ci --service $SERVICE_ID . && break
            echo "Retrying deploy for Web... ($RETRIES left)"
            RETRIES=$((RETRIES-1))
            sleep 5
          done
          if [ $RETRIES -le 0 ]; then
            echo "Web deploy failed after retries"
            exit 1
          fi
