name: CI/CD Deploy to Railway

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      API_SERVICE_ID: ${{ secrets.RAILWAY_API_SERVICE_ID }}
      WEB_SERVICE_ID: ${{ secrets.RAILWAY_WEB_SERVICE_ID }}
      RAILWAY_API_KEY: ${{ secrets.RAILWAY_API_KEY }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install Railway CLI v3.14.0
        run: |
          curl -fsSL https://github.com/railwayapp/cli/releases/download/v3.14.0/railway_3.14.0_linux_amd64.tar.gz | tar xz
          sudo mv railway /usr/local/bin/
          railway --version

      - name: Login to Railway
        run: echo $RAILWAY_API_KEY | railway login

      # ---------------- API Deploy ----------------
      - name: Deploy API
        working-directory: apps/api
        run: railway up --ci --service $API_SERVICE_ID

      # ---------------- Web Deploy ----------------
      - name: Deploy Web
        working-directory: apps/web
        run: railway up --ci --service $WEB_SERVICE_ID
