name: CI/CD Pipeline (Railway)

on:
  push:
    branches: [main]
  pull_request:

env:
  REGISTRY: ghcr.io
  IMAGE_OWNER: ${{ github.repository_owner }}

jobs:
  docker:
    name: Build & Push Docker Images
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4

      - uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & Push API
        uses: docker/build-push-action@v6
        with:
          context: .
          file: apps/api/Dockerfile
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_OWNER }}/api:latest
            ${{ env.REGISTRY }}/${{ env.IMAGE_OWNER }}/api:${{ github.run_number }}

      - name: Build & Push Web
        uses: docker/build-push-action@v6
        with:
          context: .
          file: apps/web/Dockerfile
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_OWNER }}/web:latest
            ${{ env.REGISTRY }}/${{ env.IMAGE_OWNER }}/web:${{ github.run_number }}

  deploy:
    name: Deploy API + Web to Railway
    needs: docker
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [api, web]
      max-parallel: 1
    steps:
      - uses: actions/checkout@v4

      - name: Install Railway CLI
        run: npm install -g @railway/cli

      - name: Deploy via Railway
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
        run: |
          set -e
          retries=3

          if [ "${{ matrix.service }}" == "api" ]; then
            SERVICE_PATH=apps/api
            SERVICE_ID=896433a2-649c-4d47-b397-1c2e4918b4fe
          else
            SERVICE_PATH=apps/web
            SERVICE_ID=651af99c-48dd-4d98-85f4-a0bc78710924
          fi

          until [ $retries -le 0 ]; do
            echo "Deploying ${{ matrix.service }} from $SERVICE_PATH..."
            cd $SERVICE_PATH
            if railway up --ci --service $SERVICE_ID .; then
              echo "Deployment succeeded!"
              cd ../..
              break
            fi
            retries=$((retries-1))
            echo "Retrying deploy for ${{ matrix.service }}... ($retries left)"
            sleep 10
            cd ../..
          done

          if [ $retries -le 0 ]; then
            echo "Deployment failed after multiple attempts!"
            exit 1
          fi
