name: CI

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  actions: read
  contents: write   # needed for release job (tagging, pushing)

jobs:
  verify:
    name: Lint • Test • Build (affected only)
    runs-on: ubuntu-latest

    env:
      NX_CLOUD_ACCESS_TOKEN: ${{ secrets.NX_CLOUD_ACCESS_TOKEN }}
      
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          filter: tree:0

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - run: npm ci --legacy-peer-deps
      - uses: nrwl/nx-set-shas@v4

      # Start Nx Cloud CI run
      - run: npx nx-cloud start-ci-run --distribute-on="3 linux-medium-js" --stop-agents-after="build"

      - run: npx nx affected -t lint test build

      - run: npx nx fix-ci
        if: always()

  release:
    name: Release
    runs-on: ubuntu-latest
    needs: verify   # release only runs if verify succeeds
    if: github.ref == 'refs/heads/main'

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      NX_CLOUD_ACCESS_TOKEN: ${{ secrets.NX_CLOUD_ACCESS_TOKEN }}

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - run: npm ci --legacy-peer-deps

      # Example: use semantic-release (adjust to your setup)
      - run: npx semantic-release
