name: Nx CI + CD (Final Working)

on:
  push:
    branches:
      - main

jobs:
  verify:
    name: Lint • Test • Build (affected only)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Nx Affected - Lint
        run: npx nx affected --target=lint --parallel=3

      - name: Nx Affected - Test
        run: npx nx affected --target=test --parallel=3

      - name: Nx Affected - Build
        run: npx nx affected --target=build --parallel=3

  deploy:
    name: Deploy API + Web in Parallel
    runs-on: ubuntu-latest
    needs: verify
    strategy:
      matrix:
        service: [api, web]
    steps:
      - uses: actions/checkout@v4

      - name: Install Railway CLI
        run: npm install -g @railway/cli

      - name: Deploy
        run: |
          if [ "${{ matrix.service }}" == "api" ]; then
            railway up --ci --service 896433a2-649c-4d47-b397-1c2e4918b4fe -- --dockerfile=.railway/Dockerfile.api
          else
            railway up --ci --service 651af99c-48dd-4d98-85f4-a0bc78710924 -- --dockerfile=.railway/Dockerfile.web
          fi
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
