name: CI

on:
  push:
    branches: [main]
  pull_request:

concurrency:
  group: nx-ci-${{ github.ref }}
  cancel-in-progress: true

permissions:
  actions: read
  contents: read

# Shared ENV
env:
  CI: "true"
  NX_CLOUD_ACCESS_TOKEN: ${{ secrets.NX_CLOUD_ACCESS_TOKEN }}
  NX_DISABLE_CLOUD: ${{ secrets.NX_CLOUD_ACCESS_TOKEN == '' && 'true' || 'false' }}
  REGISTRY: ghcr.io
  IMAGE_OWNER: ${{ tolower(github.repository_owner) }}

jobs:
  verify:
    name: Nx • Lint • Test • Build (affected)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          filter: tree:0
          fetch-depth: 0

      - run: npx nx start-ci-run --distribute-on="3 linux-medium-js" --stop-agents-after="build"

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - run: npm ci --legacy-peer-deps

      - uses: nrwl/nx-set-shas@v4

      - run: npx nx affected -t lint test build

      - run: npx nx fix-ci
        if: always()

  docker:
    name: Build & Push Docker (main only)
    needs: verify
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    outputs:
      api-digest: ${{ steps.push-api.outputs.digest }}
      web-digest: ${{ steps.push-web.outputs.digest }}
    steps:
      - uses: actions/checkout@v4
        with:
          filter: tree:0
          fetch-depth: 0

      - uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & push API
        id: push-api
        uses: docker/build-push-action@v6
        with:
          context: .                  # root context
          file: Dockerfile            # root Dockerfile
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_OWNER }}/api:latest
            ${{ env.REGISTRY }}/${{ env.IMAGE_OWNER }}/api:${{ github.run_number }}

      - name: Build & push Web
        id: push-web
        uses: docker/build-push-action@v6
        with:
          context: .                  # root context
          file: Dockerfile            # root Dockerfile
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_OWNER }}/web:latest
            ${{ env.REGISTRY }}/${{ env.IMAGE_OWNER }}/web:${{ github.run_number }}

  deploy:
    name: Deploy API + Web
    needs: docker
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [api, web]
      max-parallel: 1
    steps:
      - uses: actions/checkout@v4

      - name: Install Railway CLI
        run: npm install -g @railway/cli

      - name: Deploy via Railway
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
        run: |
          set -e
          retries=3
          if [ "${{ matrix.service }}" == "api" ]; then
            SERVICE_ID=896433a2-649c-4d47-b397-1c2e4918b4fe
            DOCKERFILE=Dockerfile
          else
            SERVICE_ID=651af99c-48dd-4d98-85f4-a0bc78710924
            DOCKERFILE=Dockerfile
          fi

          until [ $retries -le 0 ]; do
            echo "Deploying ${{ matrix.service }}..."
            # 👇 Railway CLI new syntax for Dockerfile
            railway up --ci --service $SERVICE_ID . -- --dockerfile $DOCKERFILE && break
            retries=$((retries-1))
            echo "Retrying deploy for ${{ matrix.service }}... ($retries left)"
            sleep 10
          done

  release-info:
    name: Release Info
    needs: deploy
    if: needs.deploy.result == 'success'
    runs-on: ubuntu-latest
    steps:
      - name: Print image digests
        run: |
          echo "API digest: ${{ needs.docker.outputs.api-digest }}"
          echo "Web digest: ${{ needs.docker.outputs.web-digest }}"
